# -*- coding: utf-8 -*-
"""Tugas-Bootcam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiVltxBksHm5Ul5yPGEdNt2SV3eochmJ
"""

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load dataset
data = load_iris()
X, y = data.data, data.target

# Train model
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# Evaluate model
y_pred = model.predict(X)
print("Accuracy:", accuracy_score(y, y_pred))